/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#eceef0",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "on-primary": "#ffffff",
        "on-background": "#191c1e",
        "primary-fixed-dim": "#93d879",
        "surface-bright": "#f7f9fb",
        "inverse-surface": "#2d3133",
        "on-error-container": "#93000a",
        "surface-variant": "#e0e3e5",
        "surface-dim": "#d8dadc",
        "primary-container": "#43832f",
        "tertiary-fixed-dim": "#bdcabe",
        "primary-fixed": "#aef592",
        "on-tertiary-container": "#f6fff5",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-fixed-variant": "#3e4a41",
        "surface-container-highest": "#e0e3e5",
        "tertiary-container": "#6b786e",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#131e17",
        "surface-container-high": "#e6e8ea",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-container": "#636467",
        "on-primary-fixed": "#042100",
        "inverse-primary": "#93d879",
        "primary": "#2a6918",
        "tertiary-fixed": "#d9e6da",
        "on-primary-container": "#f8ffef",
        "outline-variant": "#c1c9b8",
        "on-primary-fixed-variant": "#125300",
        "tertiary": "#535f56",
        "on-secondary-fixed-variant": "#454749",
        "secondary": "#5d5e61",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "on-surface": "#191c1e",
        "on-surface-variant": "#41493c",
        "outline": "#717a6b",
        "surface-tint": "#2d6c1a",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2e2e5",
        "secondary-fixed": "#e2e2e5",
        "secondary-fixed-dim": "#c6c6c9",
        "on-secondary-fixed": "#1a1c1e",
      },
      fontFamily: {
        'headline-sm': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif']
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }]
      },
      spacing: {
        'xs': '4px',
        'xl': '40px',
        'base': '8px',
        'sm': '12px',
        'gutter': '24px',
        'md': '16px',
        'margin': '32px',
        'lg': '24px'
      }
    },
  },
  plugins: [],
}
